# Production Profile - для деплоя на Гелиос со STUDS DB

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s409449
    password: 7ChhsEMmi3l6rp3x
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 4
    validate-on-migrate: false
    locations: classpath:db/migration
    out-of-order: true

server:
  port: 23561

jwt:
  secret: blps-jwt-secret-key-production-secure-256bits-minimum-change-this-in-prod

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.arekalov.blps: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.authentication: TRACE
    org.springframework.security.web: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
