spring:
  application:
    name: blps

  profiles:
    active: dev

  jersey:
    application-path: /engine-rest
    init:
      jersey.config.server.resource.validation.disable: "true"

server:
  servlet:
    context-path: /blps
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

camunda.bpm:
  spin:
    enabled: true
  authorization:
    enabled: true
  generic-properties:
    properties:
      historyTimeToLive: P180D
  deploy-changed-only: false
  enable-duplicate-filtering: false
  database:
    schema-update: true
  auto-deployment-enabled: false
  webapp:
    index-redirect-enabled: false

blps:
  bootstrap:
    admin-email: admin@ya.ru
    admin-password: admin
    admin-company-name: Admin Company
